"""Redirect rules for nginx, Apache, Vercel, Netlify and Cloudflare.

Rules come only from real data: collapsed redirect chains found in the crawl, host
canonicalization (http->https, www/non-www) and an optional user-supplied CSV map
(old,new[,status]). Broken URLs are listed as TODO comments because only you know where
they should point.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlsplit

from seoforge.crawler.crawler import CrawlResult
from seoforge.urls import path_of, same_site


@dataclass(frozen=True, slots=True)
class Rule:
    source: str  # path (with optional query)
    target: str  # absolute URL or path
    status: int = 301
    origin: str = "chain"


@dataclass(slots=True)
class RedirectPlan:
    site: str
    rules: list[Rule] = field(default_factory=list)
    force_https: bool = False
    canonical_host: str | None = None
    alt_host: str | None = None
    broken: list[str] = field(default_factory=list)


def load_map(path: Path) -> list[Rule]:
    rules = []
    with path.open(newline="", encoding="utf-8") as fh:
        for row in csv.reader(fh):
            if not row or row[0].startswith("#") or row[0].lower() in ("old", "source", "from"):
                continue
            status = int(row[2]) if len(row) > 2 and row[2].strip().isdigit() else 301
            source = path_of(row[0]) if row[0].startswith("http") else row[0]
            rules.append(Rule(source, row[1].strip(), status, "map"))
    return rules


def build_plan(crawl: CrawlResult, extra: list[Rule] | None = None) -> RedirectPlan:
    plan = RedirectPlan(site=crawl.site)
    seen: set[str] = set()
    for page in sorted(crawl.pages.values(), key=lambda p: p.url):
        if len(page.redirect_chain) > 1 and page.final_url and not page.error:
            for hop in page.redirect_chain:
                if same_site(hop.url, crawl.site) and path_of(hop.url) not in seen:
                    seen.add(path_of(hop.url))
                    target = (
                        path_of(page.final_url)
                        if same_site(page.final_url, crawl.site)
                        else page.final_url
                    )
                    plan.rules.append(Rule(path_of(hop.url), target, 301, "chain"))
    for rule in extra or []:
        if rule.source not in seen:
            seen.add(rule.source)
            plan.rules.append(rule)
    probe = crawl.probes.get("http_home")
    if (
        crawl.site.startswith("https://")
        and probe is not None
        and not probe.final_url.startswith("https://")
    ):
        plan.force_https = True
    alt = crawl.probes.get("alt_host_home")
    host = urlsplit(crawl.site).netloc
    if alt is not None and alt.status == 200 and urlsplit(alt.final_url).netloc != host:
        plan.canonical_host = host
        plan.alt_host = urlsplit(alt.url).netloc
    plan.broken = sorted(
        path_of(p.url)
        for p in crawl.pages.values()
        if 400 <= p.status < 500 and same_site(p.url, crawl.site)
    )
    return plan


def _abs(plan: RedirectPlan, target: str) -> str:
    return target if target.startswith("http") else plan.site + target


def nginx(plan: RedirectPlan) -> str:
    out = [
        "# nginx redirects generated by SEOForge - include inside the matching server { } block."
    ]
    host = urlsplit(plan.site).netloc
    if plan.force_https or plan.alt_host:
        out += ["", "# Put these server blocks at http level (outside your main server block):"]
    if plan.force_https:
        out += [
            f"server {{ listen 80; server_name {host}{' ' + plan.alt_host if plan.alt_host else ''};",
            f"  return 301 https://{host}$request_uri; }}",
        ]
    if plan.alt_host:
        out += [
            f"server {{ listen 443 ssl; server_name {plan.alt_host};",
            "  # ssl_certificate ...; ssl_certificate_key ...;",
            f"  return 301 https://{host}$request_uri; }}",
        ]
    out.append("")
    for r in plan.rules:
        if "?" in r.source:
            out.append(
                f"# skipped (query string; use a map on $request_uri): {r.source} -> {r.target}"
            )
            continue
        out.append(f"location = {r.source} {{ return {r.status} {_abs(plan, r.target)}; }}")
    out += [f"# TODO broken URL (choose a target or keep 404/410): {b}" for b in plan.broken]
    return "\n".join(out) + "\n"


def apache(plan: RedirectPlan) -> str:
    out = ["# Apache (.htaccess) redirects generated by SEOForge", "RewriteEngine On"]
    host = urlsplit(plan.site).netloc
    if plan.force_https:
        out += [
            "RewriteCond %{HTTPS} off",
            f"RewriteRule ^ https://{host}%{{REQUEST_URI}} [L,R=301]",
        ]
    if plan.alt_host:
        escaped = plan.alt_host.replace(".", "\\.")
        out += [
            f"RewriteCond %{{HTTP_HOST}} ^{escaped}$ [NC]",
            f"RewriteRule ^ https://{host}%{{REQUEST_URI}} [L,R=301]",
        ]
    for r in plan.rules:
        if "?" in r.source:
            path, query = r.source.split("?", 1)
            out += [
                f"RewriteCond %{{QUERY_STRING}} ^{query}$",
                f"RewriteRule ^{path.lstrip('/')}$ {_abs(plan, r.target)}? [L,R={r.status}]",
            ]
        else:
            out.append(f"Redirect {r.status} {r.source} {_abs(plan, r.target)}")
    out += [f"# TODO broken URL: {b}" for b in plan.broken]
    return "\n".join(out) + "\n"


def vercel(plan: RedirectPlan) -> str:
    redirects: list[dict[str, object]] = []
    host = urlsplit(plan.site).netloc
    if plan.alt_host:
        redirects.append(
            {
                "source": "/:path*",
                "has": [{"type": "host", "value": plan.alt_host}],
                "destination": f"https://{host}/:path*",
                "permanent": True,
            }
        )
    for r in plan.rules:
        if "?" in r.source:
            continue
        entry: dict[str, object] = {"source": r.source, "destination": r.target}
        if r.status in (301, 308):
            entry["permanent"] = True
        else:
            entry["statusCode"] = r.status
        redirects.append(entry)
    return json.dumps({"redirects": redirects}, indent=2) + "\n"


def netlify(plan: RedirectPlan) -> str:
    out = ["# Netlify _redirects generated by SEOForge (first match wins)"]
    host = urlsplit(plan.site).netloc
    if plan.alt_host:
        out.append(f"https://{plan.alt_host}/* https://{host}/:splat 301!")
    if plan.force_https:
        out.append(f"http://{host}/* https://{host}/:splat 301!")
    for r in plan.rules:
        if "?" not in r.source:
            out.append(f"{r.source} {r.target} {r.status}")
    out += [f"# TODO broken URL: {b}" for b in plan.broken]
    return "\n".join(out) + "\n"


def cloudflare_pages(plan: RedirectPlan) -> str:
    out = [
        "# Cloudflare Pages _redirects generated by SEOForge (same-site paths only).",
        "# Host and HTTPS redirects: enable 'Always Use HTTPS' and use a Redirect Rule.",
    ]
    for r in plan.rules:
        if "?" not in r.source:
            out.append(f"{r.source} {r.target} {r.status}")
    return "\n".join(out) + "\n"


def cloudflare_rules(plan: RedirectPlan) -> str:
    """Single Redirect rules (Rules > Redirect Rules) for any Cloudflare-proxied site."""
    out = [
        "# Cloudflare Redirect Rules (dashboard: Rules > Redirect Rules > Create rule)",
        "# Each block: 'Custom filter expression' -> 'Static' URL redirect.",
        "",
    ]
    host = urlsplit(plan.site).netloc
    if plan.alt_host:
        out += [
            f'Expression: (http.host eq "{plan.alt_host}")',
            f'Target (dynamic): concat("https://{host}", http.request.uri.path)',
            "Status: 301 · Preserve query string: on",
            "",
        ]
    for r in plan.rules:
        path = r.source.split("?", 1)[0]
        out += [
            f'Expression: (http.host eq "{host}" and http.request.uri.path eq "{path}")',
            f"Target (static): {_abs(plan, r.target)}",
            f"Status: {r.status}",
            "",
        ]
    if plan.force_https:
        out.append("HTTP -> HTTPS: SSL/TLS > Edge Certificates > Always Use HTTPS = On")
    return "\n".join(out) + "\n"


def render_all(plan: RedirectPlan) -> dict[str, str]:
    return {
        "redirects/nginx.conf": nginx(plan),
        "redirects/apache.htaccess": apache(plan),
        "redirects/vercel.json": vercel(plan),
        "redirects/netlify/_redirects": netlify(plan),
        "redirects/cloudflare-pages/_redirects": cloudflare_pages(plan),
        "redirects/cloudflare-redirect-rules.txt": cloudflare_rules(plan),
    }
