"""robots.txt generator: keeps your existing rules, adds an explicit AI-crawler policy."""

from __future__ import annotations

from datetime import UTC, datetime

from seoforge.geo.ai_bots import AI_BOTS, BY_TOKEN
from seoforge.robots import Group, RobotsTxt


def _rule_lines(group: Group) -> list[str]:
    lines = [f"{'Allow' if r.allow else 'Disallow'}: {r.path}" for r in group.rules]
    if group.crawl_delay is not None:
        lines.append(f"Crawl-delay: {group.crawl_delay:g}")
    return lines


def generate_robots(
    existing: RobotsTxt | None,
    policy: dict[str, str],
    sitemaps: list[str],
    preset: str = "custom",
) -> str:
    existing = existing or RobotsTxt("", status=404)
    out = [
        f"# robots.txt generated by SEOForge on {datetime.now(UTC):%Y-%m-%d}.",
        "# Review before deploying. robots.txt is a request, not access control.",
        "",
    ]
    ai_tokens = {t.lower() for t in policy} | set(BY_TOKEN)
    star_rules: list[str] = []
    kept_any = False
    for group in existing.groups:
        agents = [a for a in group.agents if a not in ai_tokens]
        if not agents:
            continue  # pure AI-bot group: replaced by the policy below
        if "*" in agents:
            star_rules = _rule_lines(group)
        out.extend(f"User-agent: {a}" for a in agents)
        out.extend(_rule_lines(group) or ["Disallow:"])
        out.append("")
        kept_any = True
    if not kept_any:
        out.extend(["User-agent: *", "Disallow:", ""])
    out.append(f"# --- AI crawlers (policy preset: {preset}) ---")
    out.append("# Allowed bots inherit the rules of the '*' group, because a bot that matches its")
    out.append("# own group ignores the '*' group entirely.")
    names = {b.token.lower(): b for b in AI_BOTS}
    for token, decision in policy.items():
        bot = names.get(token.lower())
        label = f"{bot.operator} - {bot.purpose}" if bot else "custom"
        out.append(f"# {token} ({label})")
        out.append(f"User-agent: {token}")
        if decision == "deny":
            out.append("Disallow: /")
        else:
            out.extend(star_rules or ["Allow: /"])
        out.append("")
    for sm in dict.fromkeys(sitemaps or existing.sitemaps):
        out.append(f"Sitemap: {sm}")
    return "\n".join(out).rstrip() + "\n"
