"""GEO checks: AI crawler access, llms.txt, citation-friendliness and entity signals."""

from __future__ import annotations

from collections.abc import Iterator

from seoforge import sources
from seoforge.checks.base import AuditContext, check
from seoforge.geo.analysis import GeoReport
from seoforge.models import Category, Effort, Issue, Severity

G = Category.GEO
AI_BOTS_DOC = "https://platform.openai.com/docs/bots"


def _geo(ctx: AuditContext) -> GeoReport | None:
    return ctx.extras.get("geo")


@check("ai-crawler-access", G)
def ai_crawler_access(ctx: AuditContext) -> Iterator[Issue]:
    geo = _geo(ctx)
    if geo is None or ctx.crawl.robots.unreachable:
        return
    if geo.policy_explicit and geo.mismatches:
        yield Issue(
            "ai-policy-mismatch",
            f"Live robots.txt differs from your AI crawler policy for {len(geo.mismatches)} bot(s)",
            Severity.MEDIUM,
            G,
            "seoforge.yaml declares a policy for these bots, but the live robots.txt does something else.",
            "Deploy the robots.txt generated by `seoforge fix` (review the diff first).",
            urls=[f"{ctx.site}/robots.txt"],
            evidence=geo.mismatches,
            source=sources.ROBOTS_TXT,
        )
    blocked = {
        b.token: b.operator for b in geo.bots if b.purpose in ("search", "user") and not b.allowed
    }
    if blocked and not geo.policy_explicit:
        yield Issue(
            "ai-search-bots-blocked",
            f"{len(blocked)} AI search/assistant crawler(s) are blocked",
            Severity.MEDIUM,
            G,
            "These bots fetch pages so AI answers can cite and link them. Blocking them removes "
            "your pages from those answers. If that is intentional, set the policy in seoforge.yaml "
            "and this finding becomes a policy check instead.",
            "Allow search/user-fetch bots (preset 'search-only' keeps training crawlers blocked).",
            urls=[f"{ctx.site}/robots.txt"],
            evidence=blocked,
            source=AI_BOTS_DOC,
        )
    if not any(b.explicit for b in geo.bots):
        yield Issue(
            "ai-policy-implicit",
            "robots.txt has no explicit rules for AI crawlers",
            Severity.LOW,
            G,
            "Every AI bot falls back to the '*' group. That works, but an explicit policy documents "
            "your choice per purpose (training vs search vs user-initiated).",
            "Choose a preset (allow-all / search-only / deny-all) and generate robots.txt with "
            "`seoforge fix --ai-policy search-only`.",
            urls=[f"{ctx.site}/robots.txt"],
            evidence={b.token: "allowed" if b.allowed else "blocked" for b in geo.bots},
            source=sources.ROBOTS_TXT,
        )


@check("llms-txt", G)
def llms_txt(ctx: AuditContext) -> Iterator[Issue]:
    geo = _geo(ctx)
    if geo is None:
        return
    if geo.llms_txt_status != 200:
        yield Issue(
            "llms-txt-missing",
            "No /llms.txt file",
            Severity.LOW,
            G,
            "llms.txt is a proposed standard that gives LLM tools a curated Markdown map of your "
            "site. No major AI provider has confirmed using it, so expect little direct effect; it "
            "is cheap to publish and helps agents and IDE tools that do read it.",
            "Publish the llms.txt (and optionally llms-full.txt / .md mirrors) from `seoforge fix`.",
            urls=[f"{ctx.site}/llms.txt"],
            evidence={"status": geo.llms_txt_status},
            source=sources.LLMS_TXT,
        )


@check("citation-friendliness", G)
def citation_friendliness(ctx: AuditContext) -> Iterator[Issue]:
    geo = _geo(ctx)
    if geo is None or not geo.citation:
        return
    low = {c.url: c.score for c in geo.citation if c.score < 40}
    if low:
        weakest = {c.url: c.components for c in geo.citation if c.url in low}
        yield Issue(
            "low-citation-friendliness",
            f"{len(low)} page(s) score below 40/100 for citation-friendliness",
            Severity.MEDIUM,
            G,
            "Heuristic: these pages have few quotable factual statements, unsourced numbers, no "
            "date or author, little structure, or content hidden behind JavaScript - all of which "
            "make it harder for AI answer engines to retrieve, quote and attribute them.",
            "Add a clear definition and specific facts, link sources for statistics, show author "
            "and updated date, use question headings with direct answers, and server-render text.",
            effort=Effort.MEDIUM,
            urls=sorted(low, key=lambda u: low[u]),
            evidence=weakest,
            source=sources.HELPFUL_CONTENT,
            estimate=True,
        )


@check("entity-signals", G)
def entity_signals(ctx: AuditContext) -> Iterator[Issue]:
    geo = _geo(ctx)
    if geo is None or geo.entity is None:
        return
    ent = geo.entity
    if not ent.same_as:
        yield Issue(
            "entity-no-sameas",
            "No sameAs profile links for your brand entity",
            Severity.MEDIUM,
            G,
            "sameAs links in Organization markup connect your site to the same entity on other "
            "platforms, helping search engines and AI systems disambiguate your brand.",
            "List official profiles under entity.same_as in seoforge.yaml and publish the "
            "Organization JSON-LD from `seoforge fix`.",
            urls=[ctx.crawl.start_url],
            source=f"{sources.G}/appearance/structured-data/organization",
        )
    if len(ent.name_variants) > 1:
        yield Issue(
            "brand-name-inconsistent",
            f"Brand name appears in {len(ent.name_variants)} variants",
            Severity.LOW,
            G,
            "og:site_name, structured data and title suffixes use different spellings of your name. "
            "Consistent naming strengthens entity recognition.",
            "Use one exact brand name everywhere (site, markup, profiles, directories).",
            evidence=ent.name_variants,
            urls=[ctx.crawl.start_url],
            estimate=True,
            source=f"{sources.G}/appearance/site-names",
        )
    if ent.missing_facts:
        yield Issue(
            "entity-facts-missing",
            "Entity facts are incomplete",
            Severity.INFO,
            G,
            "These basic facts are not set in seoforge.yaml or found in your markup, so the "
            "generated fact sheet and Organization markup leave them out.",
            "Fill in the entity section of seoforge.yaml (only with accurate facts).",
            evidence={"missing": ent.missing_facts},
            urls=[ctx.crawl.start_url],
            source=sources.SD_GENERAL,
        )
